/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#470869",
        "primary-container": "#5f2781",
        "on-primary": "#ffffff",
        "on-primary-container": "#d496f8",
        "primary-fixed": "#f5d9ff",
        "primary-fixed-dim": "#e5b4ff",
        "on-primary-fixed": "#30004b",
        "on-primary-fixed-variant": "#642c86",
        "inverse-primary": "#e5b4ff",

        "secondary": "#755a18",
        "secondary-container": "#fed889",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#785d1a",
        "secondary-fixed": "#ffdf9d",
        "secondary-fixed-dim": "#e6c275",
        "on-secondary-fixed": "#251a00",
        "on-secondary-fixed-variant": "#5b4300",

        "tertiary": "#3f1a57",
        "tertiary-container": "#57326f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ca9ee4",
        "tertiary-fixed": "#f4d9ff",
        "tertiary-fixed-dim": "#e3b5fd",
        "on-tertiary-fixed": "#2d0646",
        "on-tertiary-fixed-variant": "#5c3774",

        "surface": "#fff7ff",
        "surface-dim": "#dfd8e0",
        "surface-bright": "#fff7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f1fa",
        "surface-container": "#f3ebf4",
        "surface-container-high": "#ede6ef",
        "surface-container-highest": "#e8e0e9",
        "surface-variant": "#e8e0e9",
        "surface-tint": "#7e45a0",

        "on-surface": "#1d1a20",
        "on-surface-variant": "#4d4450",
        "inverse-surface": "#332f36",
        "inverse-on-surface": "#f6eef7",
        "background": "#fff7ff",
        "on-background": "#1d1a20",

        "outline": "#7e7481",
        "outline-variant": "#cfc2d1",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "3rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        headline: ["Geist", "sans-serif"],
        body: ["Inter", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
