/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#6D28D9",
        "primary-hover": "#5B21B6",
        "primary-container": "#7C3AED",
        "on-primary": "#ffffff",
        "on-primary-container": "#EDE9FE",
        "primary-fixed": "#F5F3FF",
        "primary-fixed-dim": "#DDD6FE",
        "on-primary-fixed": "#2E1065",
        "on-primary-fixed-variant": "#5B21B6",
        "inverse-primary": "#C4B5FD",

        "secondary": "#B45309",
        "secondary-container": "#FEF3C7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#92400E",
        "secondary-fixed": "#FDE68A",
        "secondary-fixed-dim": "#FCD34D",
        "on-secondary-fixed": "#78350F",
        "on-secondary-fixed-variant": "#92400E",

        "tertiary": "#4F46E5",
        "tertiary-container": "#EEF2FF",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#3730A3",
        "tertiary-fixed": "#E0E7FF",
        "tertiary-fixed-dim": "#C7D2FE",
        "on-tertiary-fixed": "#1E1B4B",
        "on-tertiary-fixed-variant": "#3730A3",

        "surface": "#FFFFFF",
        "surface-dim": "#F9FAFB",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F9FAFB",
        "surface-container": "#F3F4F6",
        "surface-container-high": "#E5E7EB",
        "surface-container-highest": "#D1D5DB",
        "surface-variant": "#F3F4F6",
        "surface-tint": "#7C3AED",

        "on-surface": "#111827",
        "on-surface-variant": "#4B5563",
        "inverse-surface": "#1F2937",
        "inverse-on-surface": "#F9FAFB",
        "background": "#FAFAFC",
        "on-background": "#111827",

        "outline": "#6B7280",
        "outline-variant": "#E5E7EB",

        "error": "#DC2626",
        "on-error": "#ffffff",
        "error-container": "#FEE2E2",
        "on-error-container": "#991B1B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "3rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        headline: ["Geist", "sans-serif"],
        body: ["Inter", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
